### ISSUE TITLE
Steps twice through search results

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#38] opened 2021-02-24 03:52 UTC
I think this is new in todays build. When I press F4 to cycle through search results it seems to cycle past two results on every key press.

**Comment by slynch8** [comment] 2021-02-24 10:50
I can't reproduce this. Can you check your key bindings, maybe it somehow has two entries for F4. In the last build I did change the key binding for F8 to be the same as F4, but that shouldn't have affected F4.

**Comment by Muzza** [comment] 2021-02-24 21:32
It is not happening first thing this morning. I haven't changed anything. I'll see if it happens again throughout the day.

**Comment by Muzza** [comment] 2021-02-25 02:00
It started doing it again so far through the day. Restarting 10x fixed it.

**Comment by Muzza** [comment] 2021-02-25 02:04
I can reproduce it fairly reliably by alternating between pressing F4 and clicking on various lines within the search window. Eventually something sets it off and F4 starts stepping twice.

**Comment by slynch8** [comment] 2021-03-03 13:24
fixed in (0.22.0)

**Closed by slynch8** 2021-03-03 13:24 UTC
