### ISSUE TITLE
[Feature Request] Be able to manipulate file in Workspace Tree.

### ISSUE THREAD

**Issue by Catddly** [slynch8/10x#1956] opened 2023-08-03 11:30 UTC
For now i think 10x is more like a good Text Editor instead of an IDE.
I think giving the ability to create new file inside workspace tree or remove from it will be a good feature.

I can only create a new file in my solution using Visual Studio, and only see it appear in my workspace tree after closing both Visual Studio and 10x Editor and restart 10x Editor again. This is annoying.
There is actually a sightly quicker way to see changes inside 10x workspace tree, which you create a new file inside your project using Visual Studio and then press control + shift + s to save all files. 10x will notice that project file changed and refresh the workspace tree.
However, I want to directly create and remove file inside 10x's workspace tree.

**Comment by slynch8** [comment] 2023-08-24 21:09
Yes, 10x should auto-update the workspace after you save it in VS. So no need to restart either.

**Comment by slynch8** [comment] 2023-08-24 21:09
Closing as a duplicate of https://github.com/slynch8/10x/issues/268

**Closed by slynch8** 2023-08-24 21:09 UTC
