### ISSUE TITLE
Go To Definition sometimes fails to find the correct function when the function name is overloaded

### ISSUE THREAD

**Issue by Aidanboneham** [slynch8/10x#1704] opened 2023-05-12 00:38 UTC
```c++
void OverloadedFunctionName(int Input1, int Input2)
{
    // Function 1
}

void OverloadedFunctionName(int* Input1, int Input2)
{
    // Function 2
}

int main()
{
    int *MyIntPointer = 0;
    int MySingleInt = 0;

    OverloadedFunctionName(MyIntPointer, 10);

    OverloadedFunctionName(MySingleInt, 10);

    return 0;
}
```

If you add this code to a file and open it in a project in 10x, using Go To Definition on the first call to OverloadedFunctionName in main (line 16) takes you to the correct call (Function 2). However, using Go To Definition on the second call (line 18) incorrectly takes you to Function 2, instead of Function 1.

**Comment by slynch8** [comment] 2023-05-22 10:29
closing as duplicate of https://github.com/slynch8/10x/issues/259

**Closed by slynch8** 2023-05-22 10:29 UTC
