### ISSUE TITLE
Total parser memory use

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#929] opened 2022-06-09 07:37 UTC
I ain't quite sure, but I think it has to use less memory

![image](https://user-images.githubusercontent.com/40520199/172791462-b9f68451-4ac9-4948-8968-d2f6534fa6f1.png)
\
\
\--------------------
version: 0.32.56

**Comment by Roman-Skabin** [comment] 2022-06-09 07:40
Also RAM usage:

![image](https://user-images.githubusercontent.com/40520199/172792234-320f2ea7-3c7a-4942-87aa-360640bbde3c.png)

**Comment by Roman-Skabin** [comment] 2022-06-09 07:46
Relaunching after clearing %AppData%\Roaming\10x\Workspaces folder helped

**Comment by slynch8** [comment] 2022-06-09 07:49
that's a crazy amount of memory. When the memory is high can you run the LogMemoryStats command and send me the output.

**Comment by Roman-Skabin** [comment] 2022-06-09 07:49
sure

**Comment by Roman-Skabin** [comment] 2022-06-09 08:02
Hmm, now it's not that high.

![image](https://user-images.githubusercontent.com/40520199/172796011-7e46ec41-e0b7-421a-9284-a0bc80ddd319.png)

It seems like relaunching after clearing %AppData%\Roaming\10x\Cache and %AppData%\Roaming\10x\Workspaces folders has helped.
If it happens again, I'll send you memory logs. Or you still need it?

**Comment by slynch8** [comment] 2022-06-09 08:04
no, that looks normal now. Yes, if it happens again let me know. Maybe something is leaking over time.

**Comment by slynch8** [comment] 2022-06-10 14:57
Thanks for the log. It definitely looks like some sort of leak but not tracked by my internal tracking. How long does it take to get to that state?

**Comment by Roman-Skabin** [comment] 2022-06-10 15:01
the size of dump is 114 GB. There is no way I attach it here.

**Comment by Roman-Skabin** [comment] 2022-06-10 15:04
What if I'll send you it here?
![image](https://user-images.githubusercontent.com/40520199/173094653-75d629a8-0631-426d-9c95-2492e471a4a2.png)

**Comment by Roman-Skabin** [comment] 2022-06-10 15:09
I will make an archive with the best compression. It'll take a while.

**Comment by slynch8** [comment] 2022-06-10 15:10
actually, I'm not even sure if I can open a dump that big. Before you compress it can you check that VS can handle it?

**Comment by slynch8** [comment] 2022-06-10 15:13
could you try and reproduce it and catch it earlier before it gets that big? Assuming it's a gradual leak over time

**Comment by slynch8** [comment] 2022-06-10 15:14
also, do you have any custom python scripts?

**Comment by slynch8** [comment] 2022-06-10 15:14
might be worth renaming your %appdata%\10x folder to clear out any settings

**Comment by Roman-Skabin** [comment] 2022-06-10 15:22
> also, do you have any custom python scripts?

Just that one [OverrideSettings.py](https://github.com/slynch8/10x/files/8880115/OverrideSettings.py.txt)

**Comment by Roman-Skabin** [comment] 2022-06-10 15:25
> actually, I'm not even sure if I can open a dump that big. Before you compress it can you check that VS can handle it?

I've sent it already 🙂

And yes, I've opened it with VS. It does not require that much memory:
![image](https://user-images.githubusercontent.com/40520199/173098727-b135514f-ce44-4f78-afb8-de51893d0ebf.png)

**Comment by slynch8** [comment] 2022-06-10 15:26
I do wonder if it is the script though, you've got an update function that is being called every frame

**Comment by Roman-Skabin** [comment] 2022-06-10 15:30
That's not my script, actually, I took it from this repo long ago. I'm not a python person, but it seems like it checks once per 3 second if the settings file was rewritten.

**Comment by slynch8** [comment] 2022-06-10 16:37
the parser is stuck on this file: reverse_ballistics.hpp, looks like the file might be corrupt. Can you check the last line in the file.

**Comment by Roman-Skabin** [comment] 2022-06-10 16:46
I'm out of office till tuesday already. I'll check it in a 3 days and let you know.

**Comment by slynch8** [comment] 2022-06-11 10:30
after further investigation of the crash dump I've found the problem. Fixed in (0.32.61)

**Closed by slynch8** 2022-06-11 10:30 UTC
Labels: bug, Priority 2
