### ISSUE TITLE
[Feature Request] Support multiple monitors.

### ISSUE THREAD

**Issue by Catddly** [slynch8/10x#1945] opened 2023-07-28 03:42 UTC
I try to drap a panel to my next monitor, but it seems that 10x can only be used within a single monitor.

I think this feature will make 10x more helpful.
I want a use 10x on multiple monitors and be freely draging panels around monitors.

**Comment by slynch8** [comment] 2023-08-01 11:05
closing as duplicate of https://github.com/slynch8/10x/issues/685

**Closed by slynch8** 2023-08-01 11:05 UTC
