### ISSUE TITLE
Parser and using namespace

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#16] opened 2020-12-15 01:17 UTC
The parser seems to handle 'using namespace' correctly within the same file, but not from included files.
StructA is not recognised in the below example, unless I specify 'using namespace A' inside header.h instead of header2.h

![10x_2a](https://user-images.githubusercontent.com/1583441/102155130-051ef780-3ecf-11eb-927a-0b99d76a4f62.png) ![10x_2b](https://user-images.githubusercontent.com/1583441/102155134-06502480-3ecf-11eb-80e4-e5d2ed47238f.png)

**Comment by slynch8** [comment] 2021-05-31 19:31
closing as duplicate of feature https://github.com/slynch8/10x/issues/55

**Closed by slynch8** 2021-05-31 19:31 UTC
Labels: bug
