### ISSUE TITLE
10x started to consume one core more or less continuously on a large project.

### ISSUE THREAD

**Issue by uucidl** [slynch8/10x#374] opened 2021-08-18 05:46 UTC
I'll upload a crashdump with name: "daec8a464873d447bbe4a8b10aad0c0c" in case this helps diagnosing what it's doing.

(There's no progress bar for parsing or anything of the sort)

**Comment by uucidl** [comment] 2021-08-18 05:48
(This is making my laptop quite hot at the moment)

**Comment by uucidl** [comment] 2021-08-18 05:51
I think this tends to happen after or when I switch branches in git, while 10x has opened the workspace, which changes a whole lot of files behind the scenes.

**Comment by slynch8** [comment] 2021-08-18 06:57
Thanks for the crash dump, I can see what is happening. You're right that it will be caused by lots of changes happening outside of 10x. The parser incrementally updates the symbols after the initial parse and sometimes this can get out of control, with thousands of changes. In your case it's stuck on a huge file 200,000 line file with thousands of changes. In this case you're better off just deleting the cache and starting again. I need to put some code in to detect this case and just do a full parse. To do it manually close 10x and delete %appdata%\10x\cache\parser\<workspace>\<workspace>.10x_parser_cache. You'll probably need to do this every time you switch branches until I get this fixed.

**Comment by uucidl** [comment] 2021-08-18 07:25
That's a rather curiously large file that I'm having here, I wasn't aware!

**Comment by slynch8** [comment] 2022-08-02 14:08
This should be fixed now

**Closed by slynch8** 2022-08-02 14:08 UTC
Labels: bug, Priority 2
