### ISSUE TITLE
Typos in key mapping command: MoveCursorNextWordSelect, MoveCursorNextNextSelect

### ISSUE THREAD

**Issue by SamWindell** [slynch8/10x#887] opened 2022-05-07 15:47 UTC
I have this code in my keymap file and it's working correctly (as it would in Visual Studio), but the names for the MoveCursor*Select commands were not intuitive.

```
Control Left: MoveCursorPrevWord

Control Right: MoveCursorNextWord

Control Shift Left: MoveCursorNextWordSelect

Control Shift Right: MoveCursorNextNextSelect
```

I would have thought that it should be:
- `MoveCursorPrevWordSelect` instead of `MoveCursorNextWordSelect`
- and `MoveCursorNextWordSelect` instead of `MoveCursorNextNextSelect`.

**Comment by slynch8** [comment] 2022-07-29 11:11
closing as duplicate of https://github.com/slynch8/10x/issues/897

**Closed by slynch8** 2022-07-29 11:11 UTC
Labels: bug, Priority 2
