### ISSUE TITLE
Search window opens file on top of itself

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#42] opened 2021-03-05 02:37 UTC
I think this is something you addressed months back but has returned.
If I have the search window docked in a pane, any files that are opened from double clicking on a result are opened on the same pane as the search window, rather than on the pane I have all my source code in.

**Comment by Muzza** [comment] 2021-08-23 22:26
I really miss using a docked search window, is there any chance this can be addressed sooner rather than later?

**Comment by slynch8** [comment] 2021-08-24 09:31
sorry, I don't use docked windows so I forgot about this one.
fixed (0.28.18)

**Comment by Muzza** [comment] 2022-08-29 22:45
This issue has returned again

**Comment by slynch8** [comment] 2022-08-30 09:39
I can't reproduce this. I don't think I've changed anything that would cause this. Could it be that 10x is just remembering where the file was last opened? Try closing 10x and deleting your %appdata%\10x\State\10xState.xml.bin file.

**Comment by Muzza** [comment] 2022-08-30 21:52
I have the left pane reserved for search, and rarely open any files on it at all.
The middle pane is where most of my source code is, and was the 'most recently used' when I started the search.

Try this: Open source code in middle pane, search in left pane. Close all files in middle pane. Run a search, and double click on a result. It always opens on top of the search panel. Move the opened source file to the middle panel. Double click on another search result. Again it opens on top of the search panel.
For me it was also happening when I already had dozens of source files in the center pane, but clearing the center pane first makes it easier to reproduce.
I don't think it ever makes sense to open the document on top of the docked search panel if there are any other panels available.

**Comment by slynch8** [comment] 2022-08-31 07:45
ok, I'll try that. Could you also send me your settings file - thanks.

**Comment by slynch8** [comment] 2022-09-01 19:37
I can't get it to happen. Can you check that you don't have the UI.Column0Files settings set

**Comment by slynch8** [comment] 2022-09-01 19:39
ah, I did just get it, but only if I haven't opened a cpp since starting 10x (it uses the last focused code panel). I'll make it never open over the search as you say.

**Comment by slynch8** [comment] 2022-09-01 20:26
Fixed (0.33.38)
You may need to delete your state binary file
%AppData%\10x\State\10xState.xml.bin

**Comment by Muzza** [comment] 2022-09-27 06:17
In the latest, whenever I double click on a result in the search window, the pane then switches to another tab, meaning I lose the search window. Its also started opening files on top of itself again, although it seems inconsistent.

**Comment by slynch8** [comment] 2022-09-27 07:19
That hasn't changed as far as I know, but I'll take a look later today.

**Comment by slynch8** [comment] 2022-09-27 09:49
It will close if it is floating, but if it's docked it stays open for me.

**Comment by Muzza** [comment] 2022-09-27 22:05
Its not happening when I open it up today. I'll see if it comes back.

**Comment by Muzza** [comment] 2022-10-28 00:22
It still does this but it is inconsistent. It seems to get stuck opening files on top of the search panel for a while, and eventually something that I do makes it start working normally again.
Sometimes restarting 10x fixes it, but I've also had times where restarted 10x made it start happening.

**Comment by slynch8** [comment] 2022-10-28 09:13
I've disabled all code that places a file by default now, so it should always open in column 0. So I'm not sure what could be causing this. Check you have these settings disabled:
 `RememberFilePanelPos`
`OpenFileInActivePanel`
`UI.ReopenFileInCurrentPanel`
`UI.Column0Files`
`UI.Column1Files`
`UI.Column2Files`

**Comment by Muzza** [comment] 2022-11-01 23:02
They were all disabled apart from OpenFileInActivePanel which was true.
If I change OpenFileInActivePanel to false then double clicking on a search result will always result in the file being opened on top of the search results. It seems odd to me that any user would desire this.

OpenFileInActivePanel as true works much more sensibly, but I've not been running 10x enough the last week to know whether it is still occasionally going wrong.

Here is another related bug I found when trying this out:
In column 0, dock your search window.
In column 1, open a few files, then open Settings.10x_settings
Set OpenFileInActivePanel  to false
Search for something.
Double click the result in the search list in column 0.
The file will open on top of the search panel in column 0 (maybe this is intended but seems wrong to me!), but column 1 will also change from Settings.10x_settings to one of the other open files.

**Comment by slynch8** [comment] 2022-11-02 10:58
If all those settings are false then files will always open in column 0, regardless of where any tool panels are docked. This is the design now, I originally tried to be clever about where a file would open, but that just caused bugs and unexpected behavior for people (everyone has different setups).

If you could find a repro for OpenFileInActivePanel breaking then I'd love to fix this once and for all, but I just can't get it or see how it can happen. I guess there must be a case where the last active panel value isn't being set for some reason.

> column 1 will also change from Settings.10x_settings to one of the other open files.
I tried to repro this but it didn't happen for me. Can you try it with all your settings reset to default and see if it still happens? (close 10x and rename your %appdata%\10x folder)

**Comment by slynch8** [comment] 2022-11-02 20:46
fixed (0.35.6)

**Closed by slynch8** 2022-11-02 20:46 UTC
Labels: bug, Priority 2, current, done

**Comment by Muzza** [comment] 2022-11-02 21:13
It does not appear to be doing anything different in the latest from my testing.

For what it is worth (and because this issue seems to keep coming back), I'm using 10x in the way that most code editors default to (VS Code for example).
I have a docked search window on the left, and one or two code editing panel on the right.
When any file is opened, I expect it to open up on the last used code panel. You cannot browse through search results if you search window keeps disappearing. Currently, docked search windows are useless.

I think the problem is that most editors have a dedicated search window, whereas you have a shared panel that can be search or code. I actually like that about 10x, but when a new file is opened, and OpenFileInActivePanel is true, it should not treat a search window as an 'ActivePanel' for a file to be opened on.

I'm going to try and put together some screen captures, because I can't believe this is intended behaviour. I also get different behaviour if I put the search panel on the right. 

Finally I suspect RememberFilePanelPos is not working correctly. I have it set to false, but clicking on search results opens files wherever they last were - which may be part of the problem.

**Comment by Muzza** [comment] 2022-11-02 21:21
lol, ok, the latest install overwrote my UI.Column0Files settings (they were blank before, but now contain *.cpp etc), and has added UseColumnPresets which defaults to true.
Changing UseColumnPresets to false, things are looking better.

**Comment by slynch8** [comment] 2022-11-02 21:45
Yes, I forgot to say that you'll need to set UseColumnPresets to false, I decided to enable it be default.

**Comment by slynch8** [comment] 2022-11-02 21:52
RememberFilePanelPos definitely disables the remembering. Here's the code

![image](https://user-images.githubusercontent.com/7141856/199609151-34b5281b-de89-4251-8e7c-5a08656847c4.png)

ModifyNewTabbedPanelPositionFromSettings is what handles the Column0Files settings, and does nothing if UseColumnPresets is false.

Anyway, hopefully it's all working as expected now.

One thought, you could dock the search panel to the left edge instead of putting it in the panel grid with all the file panels. I'm guessing that's what other editors do. Although there are some benefits to having it in the panel grid with everything else, such as being able to move focus to it with the key bindings.

**Comment by Muzza** [comment] 2022-11-02 22:03
Me thinking that RememberFilePanelPos was not working was almost certainly because because I didn't know UseColumnPresets was true

**Comment by slynch8** [comment] 2022-11-03 11:37
I see. Let me know if you run into any more problems.

**Comment by Muzza** [comment] 2025-11-08 04:06
I'm encountering this frustrating problem again. 
I have UseColumnPresets false and RememberFilePanelPos false.
My search window is always docked on the left. Every file I open using it will open over the search window, instead of in the middle window where my source code is.
