### ISSUE TITLE
Unreal defines missing for engine code

### ISSUE THREAD

**Issue by velaris1** [slynch8/10x#2454] opened 2024-02-14 16:18 UTC
With Unreal 5.3, `#defines` are missing (ex: `PLATFORM_WINDOWS`, `WITH_EDITOR`, etc.), causing code to show as disabled. 

This only seems to affect engine code. Using Epic's `Lyra` project template, only code found under the UE5 engine project is affected.

The `#define` is present in `Intermediate\Build\Win64\x64\UnrealEditor\Development\Launch\Definitions.h`, which is a "Forced Include", see UE5.vcxproj: 

`<ClCompile_ForcedIncludeFiles_1350>(...)\Intermediate\Build\Win64\x64\UnrealEditor\Development\Launch\Definitions.h</ClCompile_ForcedIncludeFiles_1350>`

**Comment by slynch8** [comment] 2024-02-19 13:38
I've tried it on 5.3 and it's working for me. 
eg GameEngine.cpp
![image](https://github.com/slynch8/10x/assets/7141856/2ea3e559-1b90-4dab-b860-72a62ee9856d)

**Comment by slynch8** [comment] 2024-02-19 13:39
How is your project setup, if your Lyra game in `Samples\Games`?

**Comment by velaris1** [comment] 2024-02-21 05:35
> How is your project setup, if your Lyra game in Samples\Games?

I'm using the source build of the engine, eg. compiled source synced from Epic's github.

Steps:

1) Install Unreal 5.3.2 via the Epic launcher.
2) From the Epic launcher, navigate to the Samples tab and locate the "Lyra Starter Game" thumbnail.
3) Click on "Create Project" and select a location of your choosing - wait for it to be created.
4) Navigate to the location where the project was created.
5) Right click on the .uproject and select "Switch Unreal Engine Version..."
6) Select "Source Build at (your_source_build_path)"
7) Open 10X, File->Open Solution...-> select the .sln from the location in step 4

Not sure if there's other ways to use a source engine build with a sample project.

![image](https://github.com/slynch8/10x/assets/17101352/cec7724a-3e59-42d4-9aff-828a00155532)

**Comment by slynch8** [comment] 2024-02-21 12:24
Thanks for the steps. That's the same setup as I have. In step 3, where do you put the game project, is it under the engine folder?

Also, where does goto-def go to on PLATFORM_WINDOWS.

And have you definitely set the correct config/platform?

**Comment by slynch8** [comment] 2024-02-29 14:27
I've just tried exactly the same thing and it's still working for me. Can you try closing 10x and deleting the folder in %appdata%\10x\Cache\Parser\<Worksapce>.

**Comment by velaris1** [comment] 2024-02-29 21:15
I'm still getting the issue after deleting the workspace folder under `%appdata%\10x\Cache\Parser`

I also tried deleting the source folder and recreating it using the seven steps I shared previously. It didn't help.

Are there any logs I can provide you to help diagnose this ?

**Comment by slynch8** [comment] 2024-03-07 09:26
Note for myself: the problem was caused by having an extra engine folder in the path. Need to find a better way to find the engine root folder.

Also, the defines don't work in the game project if it is outside the engine folder.

**Comment by slynch8** [comment] 2024-03-18 10:43
> Also, the defines don't work in the game project if it is outside the engine folder.
fixed (1.0.136)

**Closed by slynch8** 2024-03-18 10:43 UTC
Labels: Priority 2, Unreal Engine, done, current
