### ISSUE TITLE
Collapse #if #elif #endif blocks

### ISSUE THREAD

**Issue by Lake-Jee** [slynch8/10x#2341] opened 2024-01-08 21:26 UTC
For large #if and #elif and #endif blocks, it would be nice to de-clutter the current buffer by collapsing code within these blocks

**Comment by ggnkua** [comment] 2024-01-10 12:30
Sort of duplicate of #299

**Comment by slynch8** [comment] 2024-01-10 12:56
closing as duplicate of https://github.com/slynch8/10x/issues/2246

**Closed by slynch8** 2024-01-10 12:56 UTC
